//
// Created by alan2 on 25/02/2020.
//

#include "utils/colors.h"

const uint16_t HEART_POINT_BACKGROUND = COLOR_WHITE;
const uint16_t HEART_POINT_FOREGROUND = COLOR_RED;
const uint16_t HEART_POINT_COLOR_PAIR = 0x01;

const uint16_t HEART_LOST_BACKGROUND = COLOR_WHITE;
const uint16_t HEART_LOST_FOREGROUND = COLOR_BLACK;
const uint16_t HEART_LOST_COLOR_PAIR = 0x02;

// score
const uint16_t SCORE_BACKGROUND = COLOR_WHITE;
const uint16_t SCORE_FOREGROUND = COLOR_BLACK;
const uint16_t SCORE_COLOR_PAIR = 0x03;

#define COLOR_DARK_GREEN 10
const uint16_t GAME_BACKGROUND = COLOR_DARK_GREEN;
const uint16_t GAME_FOREGROUND = COLOR_WHITE;
const uint16_t GAME_COLOR_PAIR = 0x04;

const uint16_t POTION_LOW_BACKGROUND = COLOR_RED;
const uint16_t POTION_LOW_FOREGROUND = COLOR_RED;
const uint16_t POTION_LOW_COLOR_PAIR = 0x06;

const uint16_t POTION_MEDIUM_BACKGROUND = COLOR_BLUE;
const uint16_t POTION_MEDIUM_FOREGROUND = COLOR_BLUE;
const uint16_t POTION_MEDIUM_COLOR_PAIR = 0x07;

#define COLOR_GREY 20
const uint16_t ARMOR_LOW_BACKGROUND = COLOR_GREY;
const uint16_t ARMOR_LOW_FOREGROUND = COLOR_GREY;
const uint16_t ARMOR_LOW_COLOR_PAIR = 0x08;

const uint16_t ARMOR_MEDIUM_BACKGROUND = COLOR_YELLOW;
const uint16_t ARMOR_MEDIUM_FOREGROUND = COLOR_YELLOW;
const uint16_t ARMOR_MEDIUM_COLOR_PAIR = 0x09;

const uint16_t POWER_LOW_BACKGROUND = COLOR_GREEN;
const uint16_t POWER_LOW_FOREGROUND = COLOR_GREEN;
const uint16_t POWER_LOW_COLOR_PAIR = 0x0A;

const uint16_t POWER_MEDIUM_BACKGROUND = COLOR_MAGENTA;
const uint16_t POWER_MEDIUM_FOREGROUND = COLOR_MAGENTA;
const uint16_t POWER_MEDIUM_COLOR_PAIR = 0x0B;

#define COLOR_LIGHT_GREY 30
const uint16_t CASTLE_BACKGROUND = COLOR_LIGHT_GREY;
const uint16_t CASTLE_FOREGROUND = COLOR_BLACK;
const uint16_t CASTLE_COLOR_PAIR = 0x0C;

const uint16_t ERROR_BACKGROUND = COLOR_BLACK;
const uint16_t ERROR_FOREGROUND = COLOR_RED;
const uint16_t ERROR_COLOR_PAIR = 0x0D;

void init_color_pairs(void)
{
    init_pair(5, COLOR_WHITE, COLOR_BLACK);
    init_pair(HEART_POINT_COLOR_PAIR, HEART_POINT_FOREGROUND, HEART_POINT_BACKGROUND);
    init_pair(HEART_LOST_COLOR_PAIR, HEART_LOST_FOREGROUND, HEART_LOST_BACKGROUND);
    init_pair(SCORE_COLOR_PAIR, SCORE_FOREGROUND, SCORE_BACKGROUND);
    init_pair(POTION_LOW_COLOR_PAIR, POTION_LOW_FOREGROUND, POTION_LOW_BACKGROUND);
    init_pair(POTION_MEDIUM_COLOR_PAIR, POTION_MEDIUM_FOREGROUND, POTION_MEDIUM_BACKGROUND);
    init_pair(ARMOR_LOW_COLOR_PAIR, ARMOR_LOW_FOREGROUND, ARMOR_LOW_BACKGROUND);
    init_pair(ARMOR_MEDIUM_COLOR_PAIR, ARMOR_MEDIUM_FOREGROUND, ARMOR_MEDIUM_BACKGROUND);
    init_pair(POWER_LOW_COLOR_PAIR, POWER_LOW_FOREGROUND, POWER_LOW_BACKGROUND);
    init_pair(POWER_MEDIUM_COLOR_PAIR, POWER_MEDIUM_FOREGROUND, POWER_MEDIUM_BACKGROUND);
    init_pair(CASTLE_COLOR_PAIR, CASTLE_FOREGROUND, CASTLE_BACKGROUND);
    init_pair(ERROR_COLOR_PAIR, ERROR_FOREGROUND, ERROR_BACKGROUND);

    init_color(COLOR_DARK_GREEN, 0, 500, 0);
    init_color(COLOR_GREY, 155, 155, 155);
    init_color(COLOR_LIGHT_GREY, 230, 230, 230);
    init_pair(GAME_COLOR_PAIR, GAME_FOREGROUND, GAME_BACKGROUND);
}
