//
// Created by alan2 on 25/02/2020.
//

#include "utils/colors.h"

const uint16_t HEART_POINT_BACKGROUND = COLOR_WHITE;
const uint16_t HEART_POINT_FOREGROUND = COLOR_RED;
const uint16_t HEART_POINT_COLOR_PAIR = 0x01;

const uint16_t HEART_LOST_BACKGROUND = COLOR_WHITE;
const uint16_t HEART_LOST_FOREGROUND = COLOR_BLACK;
const uint16_t HEART_LOST_COLOR_PAIR = 0x02;

// score
const uint16_t SCORE_BACKGROUND = COLOR_WHITE;
const uint16_t SCORE_FOREGROUND = COLOR_RED;
const uint16_t SCORE_COLOR_PAIR = 0x03;

#define COLOR_DARK_GREEN 10
const uint16_t GAME_BACKGROUND = COLOR_DARK_GREEN;
const uint16_t GAME_FOREGROUND = COLOR_WHITE;
const uint16_t GAME_COLOR_PAIR = 0x04;

void init_color_pairs(void)
{
    init_pair(HEART_POINT_COLOR_PAIR, HEART_POINT_FOREGROUND, HEART_POINT_BACKGROUND);
    init_pair(HEART_LOST_COLOR_PAIR, HEART_LOST_FOREGROUND, HEART_LOST_BACKGROUND);
    init_pair(SCORE_COLOR_PAIR, SCORE_FOREGROUND, SCORE_BACKGROUND);

    init_color(COLOR_DARK_GREEN, 0, 150, 0);
    init_pair(GAME_COLOR_PAIR, GAME_FOREGROUND, GAME_BACKGROUND);
}
